action_order: simultaneous
api:
  cors_origins:
  - '*'
  host: 0.0.0.0
  port: 8000
  rate_limit: 100/minute
  reload: false
  workers: 1
available_action_types:
- none
- speak
- non-verbal communication
- action
- leave
default_model: gpt-4o-mini
enable_metrics: true
evaluators:
- config:
    max_stale_turn: 2
    max_turn_number: 20
  enabled: true
  model: null
  type: rule_based
- config:
    dimensions: sotopia
  enabled: true
  model: gpt-4o-mini
  type: llm
logging:
  backup_count: 5
  file_path: null
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10MB
max_turns: 20
metrics_port: 9090
models:
  gpt-4:
    api_base: null
    api_key: null
    custom_config: null
    max_tokens: null
    name: gpt-4
    temperature: 0.7
    timeout: 30
    type: openai
  gpt-4o-mini:
    api_base: null
    api_key: null
    custom_config: null
    max_tokens: null
    name: gpt-4o-mini
    temperature: 0.7
    timeout: 30
    type: openai
